# -*- coding: utf-8 -*-

t = '''
Prometheus Viral Clip # 2 ... Prometheus Viral Clip # 2 introducing David the Android : \
... gave the android the name David because as the name he had initially reserved for his own ... explore and Build Better Worlds with the new David 8.\" Prometheus Edit.
Months before the release of director Ridley Scott’s “Prometheus” the studio behind his big-budget science-fiction film has been building buzz ...
A video clip featuring the android David from Ridley Scott's upcoming science fiction epic Prometheus has been released.


... in the latest teaser for Ridley Scott's highly anticipated sci-fi epic Prometheus. WIRED. ... The android named David and played by a fantastically rigid-yet ...
Michael Fassbender Magneto talks 'X-Men: First Class' teases new details; Michael Fassbender eerie in David 8 'Prometheus' viral video; Chris Hemsworth ...
Months before the release of director Ridley Scott's \"Prometheus\" the studio behind his big-budget science-fiction film has been building buzz online with an ...
Fox is kicking the viral campaign for Ridley Scott's Prometheus up a notch ... advertisement for \"David\" the latest generation android from the ...
Prometheus David 8 Android Unboxed Viral Video Director Ridley Scott is pulling out all the stops in promoting his sci-fi thriller Prometheus at WonderCon 2012.
As part of a advertising campaign for the Alien prequel-ish of Ridley Scott’s Prometheus the studio has produced this mock video advert for the android that appears ...

Prometheus stumbles in answering some of its ambitious questions but its worldbuilding is breathtaking—especially Weyland android David.
As anticipation for Ridley Scott’s sci-fi movie Prometheus continues to build a new viral video has been released this time introducing us to the android David 8 ...
What is it about robots that makes them so robotic? Since the viral campaign for The Dark Knight Rises has been pretty much non-existent a true
David the Android from Prometheus. 347 likes · 15 talking about this.
Create your own images with the Prometheus Android David meme generator.
Wow. That’s the only thought we have after watching the newest “Prometheus” viral ad for the film’s David android line. Fox is really getting their marketing ...
Besides the video from above the viral website for Prometheus has been updated. There is an all new company timeline for Weyland Industries. Click here to view all ...
Michael Fassbender has opened up about his role in Prometheus. The Shame star who plays an android named David in the highly-anticipated movie from Ridley Scott ...
'Prometheus' Viral Introduces Weyland Android \"David\"; Second Russian Trailer!
With the Prometheus Blu-ray about to hit shelves android David gives us his thoughts on music movies God and Asimov's three laws of robotics.

Michael Fassbender plays an android named David in Prometheus. Ian Holm played Ash in Alien. In the first film it was a surprise to the crew and audience that the ...

David android Blade Runner David android Prometheus Don't all children really want their parents dead? Prometheus Lawrence of Arabia ...
Michael Fassbender's android David is highlighted in a new viral video for Ridley Scott's \"Prometheus\". Coming out via Mashable the faux advertisement highlights ...
Answer 1 of 2: Lawrence of Arabia. Starring Peter O'Toole. ... Prometheus (2012 movie): What was the film the android David said he liked in Prometheus?
Movie News: New Prometheus Viral Video Introduces Michael Fassbender's Android David (Prometheus Ridley Scott Michael Fassbender )
When we see the severed head and torn wiring of android David (Michael Fassbender) ... Prometheus has been written by Jon Spaihts and Damon Lindelof.
Ridley Scott’s “Prometheus” has been using viral marketing to effectively build up buzz surrounding the upcoming film. First there was the TED 2023 ...
Go here to find out. ... Scrawl of Cthulhu...by Robert Holm! Scholarly recluse — curator of weirdness — geek — contrarian — cynic misanthrope
20th Century Fox | Viral trailers for Prometheus feature David the android November 26 2012
Michael Fassbender's performance in the new viral ad for David the all-knowing adroid in Prometheus is fantastically hair raising. Although made for a movie the ...
Here is something I'm curious about. Is David an android or a cyborg?! I ask this because I'm taking into consideration the time period in which Prometheus is placed.
As part of Fox's ad campaign for \"Prometheus\" they have released a video with the android David.
“What is it about robots that makes them so robotic?” We’ve seen some very exciting reveals from the Weyland Industries Prometheus viral in the past month ...
Name (required) Mail (will not be published) (required) Website. Rules: No profanity or personal attacks. Use a valid email address or risk being banned from commenting.
Michael Fassbender can now be seen on the big screen as David the android in Ridley Scott's “Prometheus.” On Jon Stewart the other night he was asked to reveal ...

We chat with Michael Fassbender (David) about 'Prometheus' playing an android who does his own hairstyling working with Ridley Scott and the rapid rise of his career.
Prometheus Ridley Scott's 3D pseudo-prequel to Alien features an android character called David played by Michael Fassbender. And considering the new film's ...
Michael Fassbender stars as the android David in Prometheus. Credits: Courtesy Twentieth Century Fox . Tweet. 0 Email. Movies newsletter. E-mail * (  ...


PROMETHEUS Viral Continues with Android-Unboxing Video from Weyland Corp Featuring Michael Fassbender ... Find Out What David Said to the Engineer in PROMETHEUS;
David (Prometheus) Edit History; ... even taunted by Holloway's biased remarks towards him for being an android. Despite this David is able to tolerate his treatment and ...
'''

